### ISSUE TITLE
The library is not compiling on ios 64 bits

### ISSUE THREAD

**Issue by silviucpp** [paulhodge/EASTL#13]
Problem is on   eaplatform.h where because 64 bit is not defined will always reach             #error Unknown processor

  #if defined(EA_PLATFORM_IPHONE) || defined(**IPHONE**) || (defined(TARGET_OS_IPHONE) && TARGET_OS_IPHONE) || (defined(TARGET_IPHONE_SIMULATOR) && TARGET_IPHONE_SIMULATOR)
        #undef  EA_PLATFORM_IPHONE
        #define EA_PLATFORM_IPHONE 1
        #define EA_PLATFORM_NAME "iPhone"
        #define EA_ASM_STYLE_ATT
        #define EA_POSIX_THREADS_AVAILABLE 1
        #if defined(**arm**)
            #define EA_PROCESSOR_ARM
            #define EA_SYSTEM_LITTLE_ENDIAN
            #define EA_PLATFORM_DESCRIPTION "iPhone on ARM"
        #elif defined(**i386**)
            #define EA_PLATFORM_IPHONE_SIMULATOR
            #define EA_PROCESSOR_X86
            #define EA_SYSTEM_LITTLE_ENDIAN
            #define EA_PLATFORM_DESCRIPTION "iPhone simulator on x86"
        #else
            #error Unknown processor
        #endif
        #define EA_PLATFORM_MOBILE

**Comment by BSVino** [comment]
I don't have access to that platform. Patches welcome :]

**Comment by silviucpp** [comment]
You just need to add in eaplatform.h:

   #elif defined(__arm64)
            #define EA_PROCESSOR_ARM
            #define EA_SYSTEM_LITTLE_ENDIAN
            #define EA_PLATFORM_DESCRIPTION "iPhone on ARM64"
   #elif defined(__x86_64)
            #define EA_PLATFORM_IPHONE_SIMULATOR
            #define EA_PROCESSOR_X86_64
            #define EA_SYSTEM_LITTLE_ENDIAN
            #define EA_PLATFORM_DESCRIPTION "iPhone simulator on x64"

**Comment by silviucpp** [comment]
After this everything compiles fine

**Comment by BSVino** [comment]
Can you package this as a pull request please?
