### ISSUE TITLE
 faster EASTL version 2015

### ISSUE THREAD

**Issue by nyotis** [paulhodge/EASTL#18]
@paulhodge  
cpp conference rumours about a faster version of EASTL to be released as open source. Can you confirm? Would this be uploaded here? cheers

NY

**Comment by RegretBomb** [comment]
TBH, I'm not really interested unless the Strings class is now UTF-8 with proper Unicode support. Otherwise my need for a general containers library has been reducing since I've become comfortable with Concurrency and SOA style.

**Comment by BSVino** [comment]
I have no idea.

**Comment by pzychotic** [comment]
Not just a rumor. Scott Wardle of EA had talk at CppCon where he announced that EA is going to open source it for real.
Youtube Video of the talk: https://www.youtube.com/watch?v=8KIvWJUYbDA
The relevant part is around 18:30.

**Comment by nyotis** [comment]
Nice one!Nik Yotis---- On Thu, 22 Oct 2015 20:01:24 +0200  Thomas Roß<notifications@github.com> wrote ----Not just a rumor. Scott Wardle of EA had talk at CppCon where he announced that EA is going to open source it for real.Youtube Video of the talk: https://www.youtube.com/watch?v=8KIvWJUYbDAThe relevant part is around 18:30.—Reply to this email directly or view it on GitHub.
