### ISSUE TITLE
Configuration for Cygwin is incomplete?

### ISSUE THREAD

**Issue by TobiX** [paulhodge/EASTL#4]
When trying to build a project with EASTL under cygwin I run into this error:

```
[...]/include/EABase/config/eaplatform.h:461:6: #error Unknown platform
[...]/include/EABase/config/eaplatform.h:462:6: #error Unknown processor
[...]/include/EABase/config/eaplatform.h:463:6: #error Unknown endianness
```

It seems that on Cygwin only EA_PLATFORM_CYGWIN is defined. Adding EA_PLATFORM_LINUX to the compile switches manually fixes this, but I don't think that's the correct way to do things...

**Comment by BSVino** [comment]
I highly doubt that EA ever tried to build this for any compiler but Visual Studio on Windows. If adding EA_PLATFORM_LINUX works for you then that's probably the best bet.

**Comment by TobiX** [comment]
So eacompilertraits.h, eacompiler.h and eaplatform.h are just for fun?

No, I think those were maintained inside EA for different platform ports (one of those files references Maxis, so the EASTL was probably used for one of the Sim City or Sims games, which were ported to some platforms). Why there is even a configuration for cygwin (maybe: easier testing?) I don't know, but in its current state it's not usable out of the box on Cygwin...

**Comment by BSVino** [comment]
Good point, I suppose they did try Cygwin at some point. (Re-reading your post now, I realize I must not have read it properly the first time.) Anyhow, it looks like it fell out of use at some point so your guess is as good as mine.
