### ISSUE TITLE
Pull latest EASTL from gpl.ea.com

### ISSUE THREAD

**Issue by ychin** [paulhodge/EASTL#8]
The latest released EAWebKit is 12.4.2.2.2, with updated EASTL, release last year. Located at http://gpl.ea.com/simcity.html

**Comment by BSVino** [comment]
I'm traveling right now, but will do when I've touched down.

**Comment by BSVino** [comment]
Okay I've had a chance to look at it and I'm not a big fan of it. It removes support for some older compilers but doesn't add any new code other than an unfinished bitvector class. I'm thinking we should sleep on this one. Thoughts?

**Comment by ychin** [comment]
Sure. If a newer version is released later should probably reinvestigate. The old compiler support is likely not coming back though.

**Comment by johnthagen** [comment]
@BSVino @ychin

The latest release EAWebKit is 13.4.2.0.0, which is a whole new major version than when this ticket was originally opened.  Could this be pulled in?

http://gpl.ea.com/eawebkit.html

As for the debate about merging in new code versus not, I'd argue in my experience it's easier to manage smaller changes than big large ones.  To deal with the loss of old compiler support, could we tag releases of this repo that correspond to EAWebKit releases?  That way users could have the option of using the more up-to-date or an older version that supports their old compiler.

**Comment by BSVino** [comment]
The problem is that so many changes have been made to the community managed eastl that if EA’s changes are nontrivial (i havent looked) they will be a pain to merge, and that will introduce bugs. We have to either start over with the new EA version and abandon the community changes or else ignore the new one.

What are the new features?

**Comment by ychin** [comment]
Closing up as there's been an official EASTL repo for a while.
