### ISSUE TITLE
Detect C++11 with __cplusplus.

### ISSUE THREAD

**Issue by take-cheeze** [paulhodge/EASTL#9]
Since [__GXX_EXPERIMENTAL_CXX0X__  is going to ge deprecated](http://gcc.gnu.org/ml/gcc/2013-07/msg00071.html) C++11 detecting should use `__cplusplus` macro(higher than 199711L is C++11).
So `EA_COMPILER_IS_CPLUSPLUS_11_ENABLED` is more reliable now.
And `EA_COMPILER_IS_CPLUSPLUS_14_ENABLED` needs to get defined.

**Comment by BSVino** [comment]
Yeah sounds good, any volunteers? :P
